# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\dev\python3\EasyOM_Work_Assistant\UIs\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop.sizePolicy().hasHeightForWidth())
        self.stop.setSizePolicy(sizePolicy)
        self.stop.setMinimumSize(QtCore.QSize(23, 23))
        self.stop.setMaximumSize(QtCore.QSize(23, 23))
        self.stop.setText("")
        self.stop.setObjectName("stop")
        self.horizontalLayout_10.addWidget(self.stop)
        self.min = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min.sizePolicy().hasHeightForWidth())
        self.min.setSizePolicy(sizePolicy)
        self.min.setMinimumSize(QtCore.QSize(23, 23))
        self.min.setMaximumSize(QtCore.QSize(23, 23))
        self.min.setText("")
        self.min.setObjectName("min")
        self.horizontalLayout_10.addWidget(self.min)
        self.max = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max.sizePolicy().hasHeightForWidth())
        self.max.setSizePolicy(sizePolicy)
        self.max.setMinimumSize(QtCore.QSize(23, 23))
        self.max.setMaximumSize(QtCore.QSize(23, 23))
        self.max.setText("")
        self.max.setObjectName("max")
        self.horizontalLayout_10.addWidget(self.max)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.topLabel = QtWidgets.QLabel(self.centralwidget)
        self.topLabel.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.topLabel.setFont(font)
        self.topLabel.setObjectName("topLabel")
        self.horizontalLayout_2.addWidget(self.topLabel)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dateLable = QtWidgets.QLabel(self.centralwidget)
        self.dateLable.setMaximumSize(QtCore.QSize(221, 23))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.dateLable.setFont(font)
        self.dateLable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dateLable.setScaledContents(False)
        self.dateLable.setObjectName("dateLable")
        self.horizontalLayout.addWidget(self.dateLable)
        self.lcdClock = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdClock.setMinimumSize(QtCore.QSize(215, 0))
        self.lcdClock.setMaximumSize(QtCore.QSize(215, 23))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        self.lcdClock.setFont(font)
        self.lcdClock.setStatusTip("")
        self.lcdClock.setLineWidth(0)
        self.lcdClock.setDigitCount(10)
        self.lcdClock.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdClock.setObjectName("lcdClock")
        self.horizontalLayout.addWidget(self.lcdClock)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.todayTodoLabel = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.todayTodoLabel.setFont(font)
        self.todayTodoLabel.setObjectName("todayTodoLabel")
        self.verticalLayout_2.addWidget(self.todayTodoLabel)
        self.todayTodoTable = QtWidgets.QTableView(self.tab)
        self.todayTodoTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.todayTodoTable.setDragEnabled(False)
        self.todayTodoTable.setSortingEnabled(True)
        self.todayTodoTable.setObjectName("todayTodoTable")
        self.todayTodoTable.horizontalHeader().setCascadingSectionResizes(False)
        self.todayTodoTable.horizontalHeader().setMinimumSectionSize(80)
        self.verticalLayout_2.addWidget(self.todayTodoTable)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.todayDoneLabel = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.todayDoneLabel.setFont(font)
        self.todayDoneLabel.setObjectName("todayDoneLabel")
        self.verticalLayout_3.addWidget(self.todayDoneLabel)
        self.todayDoneTable = QtWidgets.QTableView(self.tab)
        self.todayDoneTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.todayDoneTable.setDragEnabled(False)
        self.todayDoneTable.setSortingEnabled(True)
        self.todayDoneTable.setObjectName("todayDoneTable")
        self.todayDoneTable.horizontalHeader().setCascadingSectionResizes(False)
        self.todayDoneTable.horizontalHeader().setMinimumSectionSize(80)
        self.verticalLayout_3.addWidget(self.todayDoneTable)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.emerAddButton = QtWidgets.QPushButton(self.tab)
        self.emerAddButton.setMinimumSize(QtCore.QSize(200, 0))
        self.emerAddButton.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(12)
        self.emerAddButton.setFont(font)
        self.emerAddButton.setObjectName("emerAddButton")
        self.horizontalLayout_4.addWidget(self.emerAddButton)
        self.pageRefreshButton = QtWidgets.QPushButton(self.tab)
        self.pageRefreshButton.setMinimumSize(QtCore.QSize(200, 0))
        self.pageRefreshButton.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(12)
        self.pageRefreshButton.setFont(font)
        self.pageRefreshButton.setObjectName("pageRefreshButton")
        self.horizontalLayout_4.addWidget(self.pageRefreshButton)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.taskListLabel = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.taskListLabel.setFont(font)
        self.taskListLabel.setObjectName("taskListLabel")
        self.verticalLayout_4.addWidget(self.taskListLabel)
        self.taskListTable = QtWidgets.QTableView(self.tab)
        self.taskListTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.taskListTable.setDragEnabled(False)
        self.taskListTable.setSortingEnabled(True)
        self.taskListTable.setObjectName("taskListTable")
        self.taskListTable.horizontalHeader().setCascadingSectionResizes(False)
        self.taskListTable.horizontalHeader().setMinimumSectionSize(80)
        self.verticalLayout_4.addWidget(self.taskListTable)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.begDateLabel = QtWidgets.QLabel(self.tab_2)
        self.begDateLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.begDateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.begDateLabel.setObjectName("begDateLabel")
        self.horizontalLayout_6.addWidget(self.begDateLabel)
        self.begDate = QtWidgets.QDateEdit(self.tab_2)
        self.begDate.setObjectName("begDate")
        self.horizontalLayout_6.addWidget(self.begDate)
        self.endDateLabel = QtWidgets.QLabel(self.tab_2)
        self.endDateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.endDateLabel.setObjectName("endDateLabel")
        self.horizontalLayout_6.addWidget(self.endDateLabel)
        self.endDate = QtWidgets.QDateEdit(self.tab_2)
        self.endDate.setObjectName("endDate")
        self.horizontalLayout_6.addWidget(self.endDate)
        self.queryButton = QtWidgets.QPushButton(self.tab_2)
        self.queryButton.setObjectName("queryButton")
        self.horizontalLayout_6.addWidget(self.queryButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.queryTable = QtWidgets.QTableView(self.tab_2)
        self.queryTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.queryTable.setObjectName("queryTable")
        self.verticalLayout_7.addWidget(self.queryTable)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.begDateLabel_2 = QtWidgets.QLabel(self.tab_3)
        self.begDateLabel_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.begDateLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.begDateLabel_2.setObjectName("begDateLabel_2")
        self.horizontalLayout_7.addWidget(self.begDateLabel_2)
        self.begDate_2 = QtWidgets.QDateEdit(self.tab_3)
        self.begDate_2.setObjectName("begDate_2")
        self.horizontalLayout_7.addWidget(self.begDate_2)
        self.endDateLabel_2 = QtWidgets.QLabel(self.tab_3)
        self.endDateLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.endDateLabel_2.setObjectName("endDateLabel_2")
        self.horizontalLayout_7.addWidget(self.endDateLabel_2)
        self.endDate_2 = QtWidgets.QDateEdit(self.tab_3)
        self.endDate_2.setObjectName("endDate_2")
        self.horizontalLayout_7.addWidget(self.endDate_2)
        self.analysisButton = QtWidgets.QPushButton(self.tab_3)
        self.analysisButton.setObjectName("analysisButton")
        self.horizontalLayout_7.addWidget(self.analysisButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.totalDoneLabel = QtWidgets.QLabel(self.tab_3)
        self.totalDoneLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.totalDoneLabel.setObjectName("totalDoneLabel")
        self.horizontalLayout_8.addWidget(self.totalDoneLabel)
        self.totalDone = QtWidgets.QLabel(self.tab_3)
        self.totalDone.setAlignment(QtCore.Qt.AlignCenter)
        self.totalDone.setObjectName("totalDone")
        self.horizontalLayout_8.addWidget(self.totalDone)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.typeNo = QtWidgets.QLabel(self.tab_3)
        self.typeNo.setAlignment(QtCore.Qt.AlignCenter)
        self.typeNo.setObjectName("typeNo")
        self.horizontalLayout_8.addWidget(self.typeNo)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 1)
        self.horizontalLayout_8.setStretch(2, 2)
        self.horizontalLayout_8.setStretch(3, 2)
        self.horizontalLayout_8.setStretch(4, 2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.workLabel = QtWidgets.QLabel(self.tab_3)
        self.workLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.workLabel.setObjectName("workLabel")
        self.horizontalLayout_9.addWidget(self.workLabel)
        self.workDays = QtWidgets.QLabel(self.tab_3)
        self.workDays.setMaximumSize(QtCore.QSize(80, 16777215))
        self.workDays.setAlignment(QtCore.Qt.AlignCenter)
        self.workDays.setObjectName("workDays")
        self.horizontalLayout_9.addWidget(self.workDays)
        self.workLabel_2 = QtWidgets.QLabel(self.tab_3)
        self.workLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.workLabel_2.setObjectName("workLabel_2")
        self.horizontalLayout_9.addWidget(self.workLabel_2)
        self.holiDays = QtWidgets.QLabel(self.tab_3)
        self.holiDays.setMaximumSize(QtCore.QSize(80, 16777215))
        self.holiDays.setAlignment(QtCore.Qt.AlignCenter)
        self.holiDays.setObjectName("holiDays")
        self.horizontalLayout_9.addWidget(self.holiDays)
        self.workLabel_3 = QtWidgets.QLabel(self.tab_3)
        self.workLabel_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.workLabel_3.setObjectName("workLabel_3")
        self.horizontalLayout_9.addWidget(self.workLabel_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EasyOM Work Assistant - Powered by Jovany Rong"))
        self.topLabel.setText(_translate("MainWindow", "EasyOM Work Assistant"))
        self.dateLable.setText(_translate("MainWindow", "year-month-day, weekday"))
        self.todayTodoLabel.setText(_translate("MainWindow", "Today\'s To-Do"))
        self.todayDoneLabel.setText(_translate("MainWindow", "Today\'s Done"))
        self.emerAddButton.setText(_translate("MainWindow", "Add An Emergency"))
        self.pageRefreshButton.setText(_translate("MainWindow", "Page Refresh"))
        self.taskListLabel.setText(_translate("MainWindow", "Task List"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Home"))
        self.begDateLabel.setText(_translate("MainWindow", "TextLabel"))
        self.endDateLabel.setText(_translate("MainWindow", "TextLabel"))
        self.queryButton.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Query"))
        self.begDateLabel_2.setText(_translate("MainWindow", "TextLabel"))
        self.endDateLabel_2.setText(_translate("MainWindow", "TextLabel"))
        self.analysisButton.setText(_translate("MainWindow", "PushButton"))
        self.totalDoneLabel.setText(_translate("MainWindow", "TextLabel"))
        self.totalDone.setText(_translate("MainWindow", "-"))
        self.typeNo.setText(_translate("MainWindow", "-"))
        self.workLabel.setText(_translate("MainWindow", "TextLabel"))
        self.workDays.setText(_translate("MainWindow", "-"))
        self.workLabel_2.setText(_translate("MainWindow", "TextLabel"))
        self.holiDays.setText(_translate("MainWindow", "-"))
        self.workLabel_3.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Analysis"))

