# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\dev\python3\EasyOM_Work_Assistant\UIs\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.topLabel = QtWidgets.QLabel(self.centralwidget)
        self.topLabel.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.topLabel.setFont(font)
        self.topLabel.setObjectName("topLabel")
        self.horizontalLayout_2.addWidget(self.topLabel)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dateLable = QtWidgets.QLabel(self.centralwidget)
        self.dateLable.setMaximumSize(QtCore.QSize(221, 23))
        self.dateLable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dateLable.setScaledContents(False)
        self.dateLable.setObjectName("dateLable")
        self.horizontalLayout.addWidget(self.dateLable)
        self.lcdClock = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdClock.setMinimumSize(QtCore.QSize(215, 0))
        self.lcdClock.setMaximumSize(QtCore.QSize(215, 23))
        self.lcdClock.setLineWidth(0)
        self.lcdClock.setDigitCount(10)
        self.lcdClock.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdClock.setObjectName("lcdClock")
        self.horizontalLayout.addWidget(self.lcdClock)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.todayTodoLabel = QtWidgets.QLabel(self.tab)
        self.todayTodoLabel.setObjectName("todayTodoLabel")
        self.verticalLayout_2.addWidget(self.todayTodoLabel)
        self.todayTodoTable = QtWidgets.QTableView(self.tab)
        self.todayTodoTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.todayTodoTable.setObjectName("todayTodoTable")
        self.verticalLayout_2.addWidget(self.todayTodoTable)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.todayDoneLabel = QtWidgets.QLabel(self.tab)
        self.todayDoneLabel.setObjectName("todayDoneLabel")
        self.verticalLayout_3.addWidget(self.todayDoneLabel)
        self.todayDoneTable = QtWidgets.QTableView(self.tab)
        self.todayDoneTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.todayDoneTable.setObjectName("todayDoneTable")
        self.verticalLayout_3.addWidget(self.todayDoneTable)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.emerAddButton = QtWidgets.QPushButton(self.tab)
        self.emerAddButton.setMaximumSize(QtCore.QSize(151, 16777215))
        self.emerAddButton.setObjectName("emerAddButton")
        self.horizontalLayout_4.addWidget(self.emerAddButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.taskListLabel = QtWidgets.QLabel(self.tab)
        self.taskListLabel.setObjectName("taskListLabel")
        self.verticalLayout_4.addWidget(self.taskListLabel)
        self.taskListTable = QtWidgets.QTableView(self.tab)
        self.taskListTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.taskListTable.setObjectName("taskListTable")
        self.verticalLayout_4.addWidget(self.taskListTable)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EasyOM Work Assistant - Powered by Jovany Rong"))
        self.topLabel.setText(_translate("MainWindow", "EasyOM Work Assistant"))
        self.dateLable.setText(_translate("MainWindow", "year-month-day, weekday"))
        self.lcdClock.setStatusTip(_translate("MainWindow", "Clock Tool"))
        self.todayTodoLabel.setText(_translate("MainWindow", "Today\'s To-Do"))
        self.todayDoneLabel.setText(_translate("MainWindow", "Today\'s Done"))
        self.emerAddButton.setText(_translate("MainWindow", "Add An Emergency"))
        self.taskListLabel.setText(_translate("MainWindow", "Task List"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Home"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Query"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Analysis"))

